version: '3.8'

services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - mongo-net
    environment:
      - MONGO_INITDB_DATABASE=ycsb

  mongo2:
    image: mongo:latest
    container_name: mongo2
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27018:27017"
    networks:
      - mongo-net
    environment:
      - MONGO_INITDB_DATABASE=ycsb

  mongo3:
    image: mongo:latest
    container_name: mongo3
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27019:27017"
    networks:
      - mongo-net
    environment:
      - MONGO_INITDB_DATABASE=ycsb

networks:
  mongo-net:
    driver: bridge